# Generated by Django 2.2.1 on 2019-06-11 01:45

from django.db import migrations, models
import django.db.models.deletion
import pyarticle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='タイトル')),
                ('author', models.CharField(max_length=256, verbose_name='作者名')),
                ('description', models.CharField(max_length=512, verbose_name='説明')),
                ('good_count', models.IntegerField(default=0, help_text='いいね', verbose_name='いいね')),
                ('access_count', models.IntegerField(default=0, help_text='表示回数', verbose_name='表示回数')),
                ('image', models.ImageField(null=True, upload_to=pyarticle.models.get_book_image_path, verbose_name='表紙画像')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256, unique=True, verbose_name='カテゴリの名前')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(default='未設定', max_length=256, verbose_name='章')),
                ('order', models.IntegerField(default=1)),
                ('access_count', models.IntegerField(default=0, help_text='表示回数', verbose_name='表示回数')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('book', models.ForeignKey(help_text='関連する本', on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Book', verbose_name='関連する本')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='表示する順番')),
                ('text', models.TextField(verbose_name='コメント')),
                ('access_count', models.IntegerField(default=0, verbose_name='アクセス数')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('chapter', models.ForeignKey(help_text='章', on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Chapter', verbose_name='章')),
            ],
        ),
        migrations.CreateModel(
            name='SiteParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(help_text='パラメーター名', max_length=256, verbose_name='パラメーター名')),
                ('value', models.CharField(help_text='パラメーターの値', max_length=1024, verbose_name='値')),
            ],
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=pyarticle.models.get_section_image_path, verbose_name='ページの画像')),
                ('section', models.ForeignKey(help_text='セクション', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Section', verbose_name='セクション')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mail', models.CharField(help_text='メールアドレス', max_length=256, null=True, verbose_name='メールアドレス')),
                ('name', models.CharField(help_text='名前', max_length=32, null=True, verbose_name='名前')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('book', models.ForeignKey(help_text='コメントする本', on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Book', verbose_name='コメントする本')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(help_text='カテゴリー', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Category', verbose_name='カテゴリー'),
        ),
    ]
