# Generated by Django 2.2.3 on 2020-02-17 12:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pyarticle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='タイトル')),
                ('description', models.CharField(max_length=512, verbose_name='説明')),
                ('good_count', models.IntegerField(default=0, help_text='いいね', verbose_name='いいね')),
                ('access_count', models.IntegerField(default=0, help_text='表示回数', verbose_name='表示回数')),
                ('image', models.ImageField(null=True, upload_to=pyarticle.models.get_book_image_path, verbose_name='表紙画像')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256, unique=True, verbose_name='カテゴリの名前')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(default='未設定', max_length=256, verbose_name='章')),
                ('order', models.IntegerField(default=1)),
                ('access_count', models.IntegerField(default=0, help_text='表示回数', verbose_name='表示回数')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('book', models.ForeignKey(help_text='関連する本', on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Book', verbose_name='関連する本')),
            ],
        ),
        migrations.CreateModel(
            name='SiteParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(help_text='パラメーター名', max_length=256, verbose_name='パラメーター名')),
                ('value', models.CharField(help_text='パラメーターの値', max_length=1024, verbose_name='値')),
                ('image', models.ImageField(null=True, upload_to=pyarticle.models.get_header_image_path, verbose_name='ヘッダ画像')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='表示する順番')),
                ('text', models.TextField(verbose_name='コメント')),
                ('access_count', models.IntegerField(default=0, verbose_name='アクセス数')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('chapter', models.ForeignKey(help_text='章', on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Chapter', verbose_name='章')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mail', models.CharField(help_text='メールアドレス', max_length=256, null=True, verbose_name='メールアドレス')),
                ('name', models.CharField(help_text='名前', max_length=32, null=True, verbose_name='名前')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('book', models.ForeignKey(help_text='コメントする本', on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Book', verbose_name='コメントする本')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(help_text='カテゴリー', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Category', verbose_name='カテゴリー'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
