# Generated by Django 2.2.1 on 2019-06-16 06:26

from django.db import migrations, models
import pyarticle.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteparams',
            name='image',
            field=models.ImageField(null=True, upload_to=pyarticle.models.get_header_image_path, verbose_name='ヘッダ画像'),
        ),
    ]
