# Generated by Django 2.2.3 on 2020-02-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256, unique=True, verbose_name='添付ファイル名')),
                ('file_path', models.CharField(max_length=256, unique=True, verbose_name='添付ファイル保存先')),
                ('book', models.ForeignKey(help_text='関連する本', on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Book', verbose_name='関連する本')),
            ],
        ),
    ]
