# Generated by Django 2.2.3 on 2020-02-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0002_attachfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttachFile',
        ),
    ]
