# Generated by Django 2.2.3 on 2020-02-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0002_siteparams_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionImage',
        ),
    ]
