# Generated by Django 3.0.8 on 2020-07-26 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0003_delete_attachfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(help_text='サイト/ブログ', max_length=256, null=True, verbose_name='サイト/ブログ')),
                ('belong', models.CharField(help_text='所属している組織・企業', max_length=256, null=True, verbose_name='所属している組織・企業')),
                ('intro', models.CharField(help_text='自己紹介', max_length=1024, null=True, verbose_name='自己紹介')),
                ('twitter', models.CharField(help_text='ツイッターID', max_length=256, null=True, verbose_name='ツイッターID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
