# Generated by Django 3.0.8 on 2020-08-16 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0007_auto_20200816_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.CharField(help_text='referer', max_length=512, null=True, verbose_name='referer')),
                ('remote_addr', models.CharField(help_text='ip_adress', max_length=128, null=True, verbose_name='ip_adress')),
                ('agent', models.CharField(help_text='agent', max_length=512, null=True, verbose_name='agent')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('section', models.ForeignKey(help_text='関連する本', on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Section', verbose_name='関連する本')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
