# Generated by Django 3.0.8 on 2020-08-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0008_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='book',
            field=models.ForeignKey(help_text='本', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Book', verbose_name='本'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='chapter',
            field=models.ForeignKey(help_text='関連するチャプター', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Chapter', verbose_name='関連するチャプター'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='section',
            field=models.ForeignKey(help_text='関連するページ', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyarticle.Section', verbose_name='関連するページ'),
        ),
    ]
