# Generated by Django 3.0.8 on 2020-08-21 13:01

from django.db import migrations, models
import pyarticle.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0009_auto_20200816_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='header_image',
            field=models.ImageField(null=True, upload_to=pyarticle.models.get_book_image_path, verbose_name='ヘッダー画像'),
        ),
    ]
