# Generated by Django 3.0.8 on 2020-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0010_book_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='表示名', max_length=256, null=True, verbose_name='表示名'),
        ),
    ]
