# Generated by Django 3.0.8 on 2020-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0012_auto_20200822_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='footer',
            field=models.TextField(null=True, verbose_name='フッター'),
        ),
    ]
