# Generated by Django 3.0.8 on 2021-06-14 19:02

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pyarticle', '0016_book_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
